# Generated by Django 2.1.5 on 2019-01-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_time_at',
            new_name='last_login_at',
        ),
    ]
